# @package _global_
defaults:
  - /data@data: lentils
  - _self_


name: statistical_based

# Pipeline reference, resolved relative to this trainrun's directory.
pipeline: ../pipeline/statistical_based.yaml


output_dir: outputs/statistical_based

# NO TRAINABLE NODES - statistical only
unfreeze_nodes: []
freeze_nodes: []
metric_nodes: []
loss_nodes: []
